CREATE DATABASE IF NOT EXISTS conscious_app;

CREATE USER IF NOT EXISTS dev;
GRANT CREATE ON DATABASE conscious_app TO dev;

CREATE USER IF NOT EXISTS prod;
GRANT CREATE ON DATABASE conscious_app TO prod;

DROP SCHEMA IF EXISTS dev_schema CASCADE;
CREATE SCHEMA dev_schema AUTHORIZATION dev;

DROP SCHEMA IF EXISTS prod_schema CASCADE;
CREATE SCHEMA prod_schema AUTHORIZATION prod;

